# configuration file for variables used in the program

ccThreshold: .7


average_radius: 43
max_radius_offset: 5

average_side_padding: 15
max_side_padding_offset: 5

minimum_distance_from_bottom_circle: 2
max_additional_distance_from_bottom_circle: 10

maximum_distance_from_edge: 10

gaussianNoiseLoc: 20
gaussianNoiseScale: 10


shouldDrawBottomWells: True
shouldDrawTopWells: False
shouldDrawCircles: False



